### ISSUE TITLE
Lock icon not showing

### ISSUE THREAD

**Issue by jamestapping** [JamesSedlacek/LocalAuthenticationKit#5]
The lock Icon and the text that is shown in the example screenshots (left of the button) is not displaying.
Tested on physical device (iPhone 13 mini)

**Comment by JamesSedlacek** [comment]
The text isn't provided with the toggle. 

Check out how I did the previews in this file:
https://github.com/JamesSedlacek/LocalAuthenticationKit/blob/main/Sources/LocalAuthenticationKit/LocalAuthToggle.swift
