### ISSUE TITLE
Not seeing the Face ID authentication

### ISSUE THREAD

**Issue by jamestapping** [JamesSedlacek/LocalAuthenticationKit#6]
I'm only ever asked for password never Face ID dialog.

Tested on physical and simulator , same result. (iPhone 13 mini)

**Comment by JamesSedlacek** [comment]
Is Face ID enabled on the device?

**Comment by JamesSedlacek** [comment]
For simulators you have to tap on 'enroll' for FaceID

**Comment by jamestapping** [comment]
Yes face-id is enabled on the device. And for the simulator I tried enrolling.

**Comment by JamesSedlacek** [comment]
Can you include screenshots/screen recordings? I'll take a look into this tomorrow

**Comment by jamestapping** [comment]
Ok will do, I just pulled it out of the project but will try again later. Thanks

**Comment by jamestapping** [comment]
Hiya, Here is a screen recording, hope it's useful. Thanks

https://github.com/JamesSedlacek/LocalAuthenticationKit/assets/68062208/916622cd-84e8-4662-aaca-ce5a97b03c77

**Comment by JamesSedlacek** [comment]
This is what Apple's documentation says. 
So I can assume that it's because biometry is either not available, not enrolled, or locked out.
LocalAuthenticationKit uses the 1st party LocalAuthentication package. 

/// Device owner will be authenticated by biometry or device passcode.
    ///
    /// @discussion Biometric or passcode authentication is required. If the biometry is available, enrolled and
    ///             not locked out, users are asked for it first. Otherwise they are asked to enter device
    ///             passcode. If passcode is not enabled, policy evaluation will fail with LAErrorPasscodeNotSet.

**Comment by jamestapping** [comment]
Ah ok, I probably need to import LocalAuthentication in my project? I'll try that
